# Dataset configuration
data_yaml_path: "dataset.yaml"

# Training parameters
epochs: 100
patience: 15
img_size: 640
cache: true

# Hyperparameter search space
batch_size_options: [8, 16, 32, 64]

optimizer_options: ["SGD", "AdamW"]

learning_rate_range: [1e-5, 1e-2]    # Learning rate range (min, max)
final_lr_factor_range: [0.01, 0.2] 

momentum_range: [0.6, 0.98]          # SGD momentum range
weight_decay_range: [1e-5, 1e-3]

warmup_epochs_options: [0, 1, 3, 5]
warmup_momentum_range: [0.0, 0.95]

# Loss function weights
box_loss_weight_range: [0.02, 0.2]
cls_loss_weight_range: [0.2, 4.0]

# Early stopping configuration for Ray Tune
grace_period: 5

# Output directories
experiment_dir: "./ray_results"
output_dir: "./models"
